parameters:
  pythonVersion: 3.7

jobs:
- job: Package

  pool:
    vmImage: ubuntu-16.04

  variables:
    python.version: ${{ parameters.pythonVersion }}

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install pip setuptools wheel -U
    displayName: Install packaging utils

  - script: python setup.py sdist bdist_wheel
    displayName: Build sdist and wheel
  
  - task: PublishPipelineArtifact@0
    displayName: Publish artifacts
    inputs:
      artifactName: dist
      targetPath: dist