parameters:
  artifactFeed: 
  pythonVersion: 3.7
  dependsOn: ['Package']

jobs:
- job: Publish
  dependsOn: ${{ parameters.dependsOn }}

  pool:
    vmImage: ubuntu-16.04

  variables:
    python.version: ${{ parameters.pythonVersion }}
    artifactFeed: ${{ parameters.artifactFeed }}

  steps:
  - checkout: none
  
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: '$(python.version)'

  - task: DownloadPipelineArtifact@0
    displayName: Download artifacts
    inputs:
      artifactName: dist
      targetPath: dist

  - script: python -m pip install twine
    displayName: Install twine

  - task: TwineAuthenticate@0
    displayName: Configure twine authentication
    inputs:
      artifactFeeds: $(artifactFeed)

  - script: twine upload -r $(artifactFeed) --config-file $(PYPIRC_PATH) dist/*
    displayName: Publish artifacts
