resources:
  repositories:
    - repository: templates
      type: github
      endpoint: GitHub
      name: noelbundick/azure-pipelines-python-templates
      ref: refs/tags/0.0.1

jobs:
- template: package.yml@templates

- template: test.yml@templates
  parameters:
    os: linux
    pythonVersions: [3.6, 3.7]

- template: test.yml@templates
  parameters:
    os: windows
    pythonVersions: [3.6, 3.7]

- template: publish.yml@templates
  parameters:
    artifactFeed: bits
    dependsOn:
    - 'Test_linux'
    - 'Test_windows'
