jobs:
- template: .azure-pipelines/jobs/build.yml
  parameters:
    os: linux
    pythonVersions: [3.6, 3.7]

- template: .azure-pipelines/jobs/build.yml
  parameters:
    os: windows
    pythonVersions: [3.6, 3.7]
