pool:
  vmImage: ubuntu-16.04

strategy:
  matrix:
    Python37:
      python.version: 3.7

steps:
- task: UsePythonVersion@0
  displayName: Use Python $(python.version)
  inputs:
    versionSpec: '$(python.version)'

- script: python -m pip install tox -U
  displayName: Install tox

- script: tox --notest
  displayName: Provision tox environments

- script: tox
  displayName: Run tox tests

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'